name: BitBucket Server to GitHub Enterprise Server migration
description: Perform a migration from BitBucket Server to GitHub Enterprise Server
title: "BitBucket Server to GitHub Enterprise Server migration"
labels: ["migration", "bitbucket-ghes"]
body:
  - type: textarea
    id: repositories
    attributes:
      label: Repositories
      description: Please enter the repositories that you would like to migrate from BitBucket Server to GitHub Enterprise Server
      placeholder: |
        your-project,your-repository-1
        your-project,your-repository-2
    validations:
      required: true
  - type: dropdown
    id: visibility
    attributes:
      label: Target repository visibility
      description: Please select the visibility for the repositories on GitHub Enterprise Server after they have been migrated
      options:
        - Private
        - Internal
    validations:
      required: true
