name: GitHub Enterprise Cloud to GitHub Enterprise Server migration
description: Perform a migration from GitHub Enterprise Cloud to GitHub Enterprise Server
title: "GitHub Enterprise Cloud to GitHub Enterprise Server migration"
labels: ["migration", "github-enterprise-cloud"]
body:
  - type: textarea
    id: repositories
    attributes:
      label: Repositories
      description: Please enter the repositories that you would like to migrate from GitHub Enterprise Cloud to GitHub Enterprise Server
      placeholder: |
        https://github.com/your-org/your-repository-1
        https://github.com/your-org/your-repository-2
    validations:
      required: true
  - type: dropdown
    id: visibility
    attributes:
      label: Target repository visibility
      description: Please select the visibility for the repositories on GitHub Enterprise Server after they have been migrated
      options:
        - Private
        - Internal
    validations:
      required: true
